<?php
$this->helper()->appendCSSFile('/static/css/datatables/dataTables.bootstrap.min.css');
$this->helper()->appendCSSFile('/static/css/datepicker/bootstrap-datetimepicker.min.css');

$this->helper()->appendJSFile('/static/js/moment/moment.min.js');
$this->helper()->appendJSFile('/static/js/datatables/dataTables.min.js');
$this->helper()->appendJSFile('/static/js/datatables/dataTables.bootstrap.min.js');
$this->helper()->appendJSFile('/static/js/datepicker/bootstrap-datetimepicker.min.js');
$this->helper()->appendJSInline('
    $(document).ready(function() {
        $(".table").DataTable({
            "order": [[ 3, "desc" ]],
            "columnDefs": [{
                "orderable": false, "targets": [0, 7],
            }],
            "columns": [
              { "width": "20px" },
              null,
              { "width": "100px" },
              { "width": "120px" },
              { "width": "120px" },
              { "width": "120px" },
              { "width": "50px" },
              { "width": "165px" }
            ]
        });
    });
');
?>
<?= $this->messages ?>
<table class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>#ID</th>
            <th>Title</th>
            <th>Category</th>
            <th>Publish date</th>
            <th>Archive date</th>
            <th>Allow comments</th>
            <th>Visible</th>
            <th></th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>#ID</th>
            <th>Title</th>
            <th>Category</th>
            <th>Publish date</th>
            <th>Archive date</th>
            <th>Allow comments</th>
            <th>Visible</th>
            <th></th>
        </tr>
        <tr>
            <td colspan="8">
                <div class="btn-toolbar" role="toolbar" aria-label="...">
                    <div class="btn-group pull-left" role="group" aria-label="...">
                        <button type="button" class="btn btn-success"><?= $this->translate('add') ?></button>
                    </div>
                    <div class="btn-group pull-right" role="group" aria-label="...">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <?= $this->translate('with_selected') ?> <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </div>
                </div>
            </td>
        </tr>
    </tfoot>
    <tbody>
    <?php foreach ($this->articles as $article): ?>
        <tr>
            <td><input type="checkbox" value="<?= $article->id ?>"></td>
            <td><?= $article->title ?></td>
            <td><?= $article->name ?></td>
            <td><?= $article->publish_date ?></td>
            <td><?= strlen($article->archive_date) ? $article->archive_date : '<span class="label label-default">' . $this->translate('no archive date') . '</span>' ?></td>
            <td><?= $article->allow_comments ? '<span class="label label-success">' . $this->translate('yes') . '</span>' : '<span class="label label-danger">' . $this->translate('no') . '</span>' ?></td>
            <td><?= $article->is_online ? '<span class="label label-success">' . $this->translate('yes') . '</span>' : '<span class="label label-danger">' . $this->translate('no') . '</span>' ?></td>
            <td><a href="/admin/article/edit/<?= $article->id ?>" class="btn btn-sm btn-default"><?= $this->translate('edit') ?></a> <a href="/admin/article/delete/<?= $this->article_id ?>" class="btn btn-sm btn-danger"><?= $this->translate('delete') ?></a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
