<div class="modal fade" id="singleModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><?= $this->translate('delete ' . $this->modulename . '') ?></h4>
            </div>
            <div class="modal-body">
                <?= $this->translate('delete ' . $this->modulename . ' confirmation') ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?= $this->translate('Cancel') ?></button>
                <button type="button" class="btn btn-danger"><?= $this->translate('delete') ?></button>
            </div>
        </div>
    </div>
</div>
<?= $this->messages ?>
<form action="" method="post">
    <table class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <?php foreach($this->fields as $field): ?>
                    <?php if ($field['type'] == 'primary_key'): ?>
                        <th>#<?= $this->translate($field['label']) ?></th>
                    <?php else: ?>
                        <th><?= $this->translate($field['label']) ?></th>
                    <?php endif; ?>
                <?php endforeach; ?>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->items as $k => $item): ?>
            <tr>
                <td><input type="checkbox" value="<?= $k ?>"></td>
                <td><?= $item['keyword'] ?></td>
                <td>
                    <?php foreach ($this->languages as $language): ?>
                        <textarea name="<?= $this->modulename ?>[<?= $k ?>][<?= $language->id ?>]" class="form-control" rows="1"><?= isset($item['languages'][$language->id]) ? $item['languages'][$language->id] : '' ?></textarea>
                    <?php endforeach; ?>
                </td>

            </tr>
        <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <?php foreach($this->fields as $key => $field): ?>
                    <?php if ($field['type'] == 'primary_key'): ?>
                        <th>#<?= $this->translate($field['label']) ?></th>
                    <?php else: ?>
                        <th><?= $this->translate($field['label']) ?></th>
                    <?php endif; ?>
                <?php endforeach; ?>
            </tr>
            <tr>
                <td colspan="8">
                    <div class="btn-toolbar" role="toolbar" aria-label="...">
                        <div class="btn-group pull-left" role="group" aria-label="...">
                            <?php if ($this->permissions['update']): ?>
                                <button type="submit"  class="btn btn-xl btn-primary"><?= $this->translate('save') ?></button>
                            <?php endif; ?>
                        </div>
                    </div>
                </td>
            </tr>
        </tfoot>
    </table>
</form>