<?= $this->messages ?>
<form class="form-horizontal" method="post">
    <div class="form-group">
        <label for="" class="col-sm-2 control-label"><?= $this->translate('username') ?></label>
        <div class="col-sm-10">
            <input type="text" name="username" required class="form-control datetime publish_date" value="<?= $this->user->username ?>">
        </div>
    </div>
    <div class="form-group">
        <label for="" class="col-sm-2 control-label"><?= $this->translate('emailaddress') ?></label>
        <div class="col-sm-10">
            <input type="text" name="emailaddress" required class="form-control datetime archive_date" value="<?= $this->user->emailaddress ?>">
        </div>
    </div>
    <div class="form-group">
        <label for="" class="col-sm-2 control-label"><?= $this->translate('user_role') ?></label>
        <div class="col-sm-10">
            <table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <?php foreach($this->actions as $action): ?>
                            <th><?= $this->translate($action->name . '_action') ?></th>
                        <?php endforeach; ?>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($this->modules as $module): ?>
                    <tr>
                        <td><?= $this->translate($module->name . '_module') ?></td>
                        <?php foreach($this->actions as $action): ?>
                            <td>
                                <input <?= ((int) $this->user->user_roles[$module->id] & (int) $action->value) == (int) $action->value ? 'checked' : '' ?> name="user_role[<?= $module->id ?>][<?= $action->id ?>]" value="<?= $action->value ?>" type="checkbox">
                            </td>
                        <?php endforeach; ?>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="form-group">
        <label for="" class="col-sm-2 control-label"><?= $this->translate('group') ?></label>
        <div class="col-sm-10">
            <select name="group_id" class="form-control">
                <option value="0"><?= $this->translate('choose_group') ?></option>
                <?php foreach($this->groups as $group): ?>
                    <option <?= $this->user->group_id == $group->id ? 'selected' : '' ?> value="<?= $group->id ?>"><?= $group->name ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <div class="checkbox">
                <label>
                    <input name="is_enabled" <?= $this->user->is_enabled ? 'checked' : '' ?> value="1" type="checkbox"> <?= $this->translate('is_enabled') ?>
                </label>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-xl btn-primary"><?= $this->translate('save') ?></button>
        </div>
    </div>
</form>
