<?php
$this->helper()->appendCSSFile('/static/css/datatables/dataTables.bootstrap.min.css');

$this->helper()->appendJSFile('/static/js/moment/moment.min.js');
$this->helper()->appendJSFile('/static/js/datatables/dataTables.min.js');
$this->helper()->appendJSFile('/static/js/datatables/dataTables.bootstrap.min.js');
$this->helper()->appendJSInline('
    $(document).ready(function() {
        $(".table").DataTable({
            "language": '. $this->translate('datatable_language') .',
            "order": [[ 1, "desc" ]],
            "columnDefs": [{
                "orderable": false, "targets": [0, 5],
            }],
            "columns": [
              { "width": "20px" },
              null,
              null,
              null,
              { "width": "90px"},
              { "width": "195px" }
            ]
        });
        $(".delete-single").on("click", function() {
            $("#singleModal").modal({backdrop: "static"});
        });
    });
');
?>
<?= $this->partial('admin_index_table.phtml', array(
    'modulename' => 'user',
    'fields' => array(
        'id' => array(
            'label' => 'ID',
            'type' => 'primary_key',
        ),
        'username' => array(
            'label' => 'username',
            'type' => 'string',
        ),
        'emailaddress' => array(
            'label' => 'emailaddress',
            'type' => 'string',
        ),
        'name' => array(
            'label' => 'group',
            'type' => 'string',
        ),
        'is_enabled' => array(
            'label' => 'is_enabled',
            'type' => 'boolean',
        ),
    ),
    'items' => $this->users,
    'messages' => $this->messages,
)) ?>