<?php
$this->_helper->appendCSSInline('
.form-signin {
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}
.form-signin .form-signin-heading,
.form-signin .checkbox {
  margin-bottom: 10px;
}
.form-signin .checkbox {
  font-weight: normal;
}
.form-signin .form-control {
  position: relative;
  height: auto;
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
  padding: 10px;
  font-size: 16px;
}
.form-signin .form-control:focus {
  z-index: 2;
}
.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
');
?>
<form class="form-signin" method="post">
    <?= $this->_messenger->display($this->partial('alert.phtml'), 'login') ?>
    <h2 class="form-signin-heading"><?= $this->translate('sign in header') ?></h2>
    <label for="inputEmail" class="sr-only"><?= $this->translate('username or email address') ?></label>
    <input type="text" name="username" id="inputEmail" class="form-control" placeholder="<?= $this->translate('username or email address') ?>" required autofocus value="<?= isset($this->post['username']) ? $this->post['username'] : '' ?>">
    <label for="inputPassword" class="sr-only"><?= $this->translate('password') ?></label>
    <input type="password" name="password" id="inputPassword" class="form-control" placeholder="<?= $this->translate('password') ?>" required>
    <div class="checkbox">
        <label>
            <input name="rememberme" type="checkbox" value="remember-me"> <?= $this->translate('remember me') ?>
        </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" name="login" type="submit"><?= $this->translate('sign in') ?></button>
    <a href="<?= $this->_router->getURLByRouteName('admin/request-reset-password') ?>" class="btn btn-lg btn-default btn-block"><?= $this->translate('forgot password') ?></a>
</form>