<?php
$this->_helper->appendCSSInline('
.form-signin {
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}
.form-signin .form-signin-heading,
.form-signin .checkbox {
  margin-bottom: 10px;
}
.form-signin .checkbox {
  font-weight: normal;
}
.form-signin .form-control {
  position: relative;
  height: auto;
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
  padding: 10px;
  font-size: 16px;
}
.form-signin .form-control:focus {
  z-index: 2;
}
.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
');
?>
<?= $this->_messenger->display($this->partial('alert.phtml'), 'passwordreset') ?>
<form class="form-signin" method="post">
    <h2 class="form-signin-heading"><?= $this->translate('reset password header') ?></h2>
    <label for="inputEmail" class="sr-only"><?= $this->translate('email address') ?></label>
    <input type="text" name="emailaddress" id="inputEmail" class="form-control" placeholder="<?= $this->translate('email address') ?>" required autofocus>
    <button class="btn btn-lg btn-primary btn-block" name="requestresetpassword" type="submit"><?= $this->translate('reset password') ?></button>
</form>