<?php
$this->helper()->appendCSSFile('/static/css/datatables/dataTables.bootstrap.min.css');

$this->helper()->appendJSFile('/static/js/moment/moment.min.js');
$this->helper()->appendJSFile('/static/js/datatables/dataTables.min.js');
$this->helper()->appendJSFile('/static/js/datatables/dataTables.bootstrap.min.js');
$this->helper()->appendJSInline('
    $(document).ready(function() {
        $(".table").DataTable({
            "language": '. $this->translate('datatable_language') .',
            "order": [[ 3, "desc" ]],
            "columnDefs": [{
                "orderable": false, "targets": [0, 7],
            }],
            "columns": [
              { "width": "20px" },
              null,
              { "width": "80px" },
              { "width": "115px" },
              { "width": "115px" },
              { "width": "130px" },
              { "width": "90px" },
              { "width": "195px" }
            ]
        });
        $(".delete-single").on("click", function() {
            $("#singleModal").modal({backdrop: "static"});
        });
    });
');
?>
<?= $this->partial('admin_index_table.phtml', array(
    'modulename' => 'article',
    'fields' => array(
        'id' => array(
            'label' => 'ID',
            'type' => 'primary_key',
        ),
        'title' => array(
            'label' => 'title',
            'type' => 'string',
        ),
        'name' => array(
            'label' => 'category',
            'type' => 'string',
        ),
        'publish_date' => array(
            'label' => 'publish_date',
            'type' => 'string',
        ),
        'archive_date' => array(
            'label' => 'archive_date',
            'type' => 'string',
        ),
        'allow_comments' => array(
            'label' => 'allow_comments',
            'type' => 'boolean',
        ),
        'is_online' => array(
            'label' => 'is_online',
            'type' => 'boolean',
        ),
    ),
    'items' => $this->articles,
    'messages' => $this->messages,
)) ?>
