-- MySQL Script generated by MySQL Workbench
-- 10/25/16 17:34:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rhmvc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rhmvc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rhmvc` DEFAULT CHARACTER SET utf8 ;
USE `rhmvc` ;

-- -----------------------------------------------------
-- Table `rhmvc`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhmvc`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhmvc`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhmvc`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `emailaddress` VARCHAR(50) NOT NULL,
  `groups_id` INT NOT NULL,
  PRIMARY KEY (`id`, `groups_id`),
  INDEX `fk_users_groups_idx` (`groups_id` ASC),
  CONSTRAINT `fk_users_groups`
    FOREIGN KEY (`groups_id`)
    REFERENCES `rhmvc`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhmvc`.`modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhmvc`.`modules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `controller` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhmvc`.`actions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhmvc`.`actions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `value` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhmvc`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhmvc`.`user_roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `modules_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `actions_id` INT NOT NULL,
  PRIMARY KEY (`id`, `modules_id`, `actions_id`),
  INDEX `fk_user_roles_modules1_idx` (`modules_id` ASC),
  INDEX `fk_user_roles_users1_idx` (`users_id` ASC),
  INDEX `fk_user_roles_actions1_idx` (`actions_id` ASC),
  CONSTRAINT `fk_user_roles_modules1`
    FOREIGN KEY (`modules_id`)
    REFERENCES `rhmvc`.`modules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_roles_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `rhmvc`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_roles_actions1`
    FOREIGN KEY (`actions_id`)
    REFERENCES `rhmvc`.`actions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhmvc`.`group_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhmvc`.`group_roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `actions_id` INT NOT NULL,
  `groups_id` INT NOT NULL,
  `modules_id` INT NOT NULL,
  PRIMARY KEY (`id`, `actions_id`, `modules_id`),
  INDEX `fk_group_roles_actions1_idx` (`actions_id` ASC),
  INDEX `fk_group_roles_groups1_idx` (`groups_id` ASC),
  INDEX `fk_group_roles_modules1_idx` (`modules_id` ASC),
  CONSTRAINT `fk_group_roles_actions1`
    FOREIGN KEY (`actions_id`)
    REFERENCES `rhmvc`.`actions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_roles_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `rhmvc`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_roles_modules1`
    FOREIGN KEY (`modules_id`)
    REFERENCES `rhmvc`.`modules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
