-- MySQL Script generated by MySQL Workbench
-- 10/31/16 17:12:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rhmvc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rhmvc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rhmvc` DEFAULT CHARACTER SET utf8 ;
USE `rhmvc` ;

-- -----------------------------------------------------
-- Table `rhmvc`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhmvc`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhmvc`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhmvc`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `emailaddress` VARCHAR(50) NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`, `group_id`),
  INDEX `fk_users_groups_idx` (`group_id` ASC),
  CONSTRAINT `fk_users_groups`
    FOREIGN KEY (`group_id`)
    REFERENCES `rhmvc`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhmvc`.`modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhmvc`.`modules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `controller` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhmvc`.`actions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhmvc`.`actions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `value` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhmvc`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhmvc`.`user_roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `module_id` INT NOT NULL,
  `action_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `module_id`, `action_id`, `users_id`),
  INDEX `fk_user_roles_modules1_idx` (`module_id` ASC),
  INDEX `fk_user_roles_actions1_idx` (`action_id` ASC),
  INDEX `fk_user_roles_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_user_roles_modules1`
    FOREIGN KEY (`module_id`)
    REFERENCES `rhmvc`.`modules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_roles_actions1`
    FOREIGN KEY (`action_id`)
    REFERENCES `rhmvc`.`actions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_roles_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `rhmvc`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhmvc`.`group_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhmvc`.`group_roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action_id` INT NOT NULL,
  `module_id` INT NOT NULL,
  `groups_id` INT NOT NULL,
  PRIMARY KEY (`id`, `action_id`, `module_id`, `groups_id`),
  INDEX `fk_group_roles_actions1_idx` (`action_id` ASC),
  INDEX `fk_group_roles_modules1_idx` (`module_id` ASC),
  INDEX `fk_group_roles_groups1_idx` (`groups_id` ASC),
  CONSTRAINT `fk_group_roles_actions1`
    FOREIGN KEY (`action_id`)
    REFERENCES `rhmvc`.`actions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_roles_modules1`
    FOREIGN KEY (`module_id`)
    REFERENCES `rhmvc`.`modules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_roles_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `rhmvc`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhmvc`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhmvc`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `is_online` TINYINT(1) NOT NULL,
  `is_enabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhmvc`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhmvc`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `publish_date` DATETIME NOT NULL,
  `archive_date` DATETIME NULL,
  `is_online` TINYINT(1) NOT NULL,
  `allow_comments` TINYINT(1) NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `category_id`),
  INDEX `fk_arcticles_categories1_idx` (`category_id` ASC),
  CONSTRAINT `fk_arcticles_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `rhmvc`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhmvc`.`languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhmvc`.`languages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iso_code` VARCHAR(2) NOT NULL,
  `is_online` TINYINT(1) NOT NULL,
  `is_default` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhmvc`.`category_contents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhmvc`.`category_contents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `language_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `language_id`, `category_id`),
  INDEX `fk_category_contents_languages1_idx` (`language_id` ASC),
  INDEX `fk_category_contents_categories1_idx` (`category_id` ASC),
  CONSTRAINT `fk_category_contents_languages1`
    FOREIGN KEY (`language_id`)
    REFERENCES `rhmvc`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_contents_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `rhmvc`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhmvc`.`article_contents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhmvc`.`article_contents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `content` TEXT NULL,
  `language_id` INT NOT NULL,
  `article_id` INT NOT NULL,
  PRIMARY KEY (`id`, `language_id`, `article_id`),
  INDEX `fk_articles_content_languages1_idx` (`language_id` ASC),
  INDEX `fk_articles_content_arcticles1_idx` (`article_id` ASC),
  CONSTRAINT `fk_articles_content_languages1`
    FOREIGN KEY (`language_id`)
    REFERENCES `rhmvc`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_content_arcticles1`
    FOREIGN KEY (`article_id`)
    REFERENCES `rhmvc`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhmvc`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhmvc`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author_name` VARCHAR(50) NULL,
  `content` TEXT NOT NULL,
  `post_date` DATETIME NOT NULL,
  `is_online` TINYINT(1) NOT NULL,
  `user_id` INT NOT NULL,
  `arcticle_id` INT NOT NULL,
  PRIMARY KEY (`id`, `arcticle_id`),
  INDEX `fk_comments_users1_idx` (`user_id` ASC),
  INDEX `fk_comments_arcticles1_idx` (`arcticle_id` ASC),
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `rhmvc`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_arcticles1`
    FOREIGN KEY (`arcticle_id`)
    REFERENCES `rhmvc`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
