<?php
    $this->helper->appendJSFile('ckeditor/commentform-config.js');
    $this->helper->appendJSFIle('ckeditor/adapters/jquery.js');
    $this->helper->appendJSFIle('ckeditor/ckeditor.js');
    $this->helper->appendJSInline('
         $("#message").ckeditor(config);
    ');

?>
<form class="form-horizontal" action="" method="post">
  <div class="form-group">
    <label for="name" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <input id="name" type="text" name="author_name" class="form-control" placeholder="Name" value="<?= $this->comment->author_name ?>">
        <?= isset($this->comment->errors) && null !== $this->comment->errors->on('author_name') ? $this->partial('alert.phtml', ['alert_type' => 'alert-danger', 'message' => $this->comment->errors->on('author_name')]) : '' ?>
    </div>
  </div>
  <div class="form-group">
    <label for="message" class="col-sm-2 control-label">Message</label>
    <div class="col-sm-10">
        <textarea id="message" rows="7" class="form-control" name="content"><?= $this->comment->content ?></textarea>
        <?= isset($this->comment->errors) && null !== $this->comment->errors->on('content') ? $this->partial('alert.phtml', ['alert_type' => 'alert-danger', 'message' => $this->comment->errors->on('content')]) : '' ?>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" name="add_comment" class="btn btn-primary">Add comment</button>
    </div>
  </div>
</form>
