<hr>
<div class="row">
    <div class="col-md-12">
        <?php foreach ($this->comments as $comment): ?>
            <div class="comment">
                <strong><?= $comment->user instanceof \User ? $comment->user->username : $comment->author_name ?> on <?= strftime('%A, %e %B %Y', $comment->post_date->getTimestamp()) ?></strong>:<br>
                <?= $comment->content ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<hr>
