<?php

$this->helper->appendJSFile('datatables/datatables.min.js');
$this->helper->appendJSFile('datatables/datatables.bootstrap.min.js');
$this->helper->appendJSInline('
    $(document).ready(function() {
        $(".table").DataTable({
            "language": ' . $this->translate('datatable_language') . ',
            "order": [[ 3, "desc" ]],
            "columnDefs": [{
                "orderable": false, "targets": [0, 6]
            }],
            "columns": [
              { "width": "20px" },
              null,
              { "width": "80px" },
              { "width": "110px" },
              { "width": "80px" },
              { "width": "80px" },
              { "width": "160px" }
            ]
        });
        $(".delete-single").on("click", function() {
            $("#singleModal").modal({backdrop: "static"});
        });
    });
');
$this->helper->appendCSSFile('datatables/datatables.min.css');
?>
<?=

$this->partial('admin_index_table.phtml', [
    'fields'        => [
            [
            'field' => 'id',
            'type'  => 'primary_key',
            'label' => 'ID'
        ],
            [
            'field' => 'article_contents[0]->title',
            'type'  => '',
            'label' => 'Title'
        ],
            [
            'field' => 'category->category_contents[0]->name',
            'type'  => '',
            'label' => 'Category'
        ],
            [
            'field' => 'publish_date',
            'type'  => '',
            'label' => 'Publish Date'
        ],
            [
            'field' => 'is_online',
            'type'  => 'boolean',
            'label' => 'Online'
        ],
            [
            'field' => 'allow_comments',
            'type'  => 'boolean',
            'label' => 'Allow Comments'
        ]
    ],
    'messages'      => null,
    'items'         => $this->articles,
    'modulename'    => 'blog',
    'modulehandler' => 'articles',
    'permissions'   => [
        'read'   => true,
        'create' => true,
        'update' => true,
        'delete' => true
    ]
]);
?>
