<?php

$this->_helper->appendJSFile('datatables/datatables.min.js');
$this->_helper->appendJSFile('datatables/datatables.bootstrap.min.js');
$this->_helper->appendJSInline('
    $(document).ready(function() {
        $(".table").DataTable({
            "language": ' . $this->translate('datatable_language') . ',
            "order": [[ 3, "desc" ]],
            "columnDefs": [{
                "orderable": false, "targets": [0, 6]
            }],
            "columns": [
              { "width": "20px" },
              null,
              { "width": "80px" },
              { "width": "110px" },
              { "width": "65px" },
              { "width": "140px" },
              { "width": "160px" }
            ]
        });
    });
');
$this->_helper->appendCSSFile('datatables/datatables.min.css');
echo $this->partial('admin_index_table.phtml', [
    'fields' => [
        [
            'field' => 'id',
            'type' => 'primary_key',
            'label' => 'ID'
        ],
        [
            'field' => 'article_contents[0]->title',
            'type' => '',
            'label' => 'Title'
        ],
        [
            'field' => 'category->category_contents[0]->name',
            'type' => '',
            'label' => 'Category'
        ],
        [
            'field' => 'publish_date',
            'type' => '',
            'label' => 'Publish Date'
        ],
        [
            'field' => 'is_online',
            'type' => 'boolean',
            'label' => 'Online'
        ],
        [
            'field' => 'allow_comments',
            'type' => 'boolean',
            'label' => 'Allow Comments'
        ]
    ],
    'items' => $this->articles,
    'modulename' => 'blog',
    'modulehandler' => 'articles',
    'permissions' => $this->permissions
]);
