<?php
$this->_helper->appendJSInline('var CKEDITOR_BASEPATH = "/static/js/ckeditor/";');
$this->_helper->appendJSFile('ckeditor/ckeditor.js');
$this->_helper->appendJSFile('ckeditor/adapters/jquery.js');
$this->_helper->appendJSFile('moment-with-locales.js');
$this->_helper->appendJSFile('datetimepicker/datetimepicker.min.js');
$this->_helper->appendJSInline('
    $(document).ready(function() {
        $(".datetime").datetimepicker({
            format: "YYYY-MM-DD HH:mm:ss"
        });
        $(".datetime2").datetimepicker({
            useCurrent: false,
            format: "YYYY-MM-DD HH:mm:ss"
        });
        $(".publish_date").on("dp.change", function (e) {
            $(".archive_date").data("DateTimePicker").minDate(e.date);
        });
        $(".archive_date").on("dp.change", function (e) {
            $(".publish_date").data("DateTimePicker").maxDate(e.date);
        });

        $(".publish_date").trigger("dp.change");
        $(".ckeditor").ckeditor({language: "en"});
    });
');

$this->_helper->appendCSSFile('datetimepicker/datetimepicker.min.css');
?>
<form class="form-horizontal" method="post">
    <div>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <?php foreach ($this->languages as $language): ?>
                <li role="presentation" <?= $language->is_default ? 'class="active"' : '' ?>><a href="#<?= $language->iso_code ?>" aria-controls="<?= $language->iso_code ?>" role="tab" data-toggle="tab"><?= $this->translate($language->iso_code) ?></a></li>
            <?php endforeach; ?>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <?php foreach ($this->languages as $language): ?>
                <div role="tabpanel" class="tab-pane <?= $language->is_default ? 'active' : '' ?>" id="<?= $language->iso_code ?>">
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <div class="checkbox">
                                <label>
                                    <?php if ($language->is_default): ?>
                                        <input type="hidden" name="language[<?= $language->id ?>][is_online]" value="1">
                                    <?php else: ?>
                                        <input type="hidden" name="language[<?= $language->id ?>][is_online]" value="0">
                                    <?php endif; ?>
                                    <input type="checkbox" name="language[<?= $language->id ?>][is_online]" value="1" <?= $language->is_default ? 'checked disabled' : (isset($this->post['language'][$language->id]['is_online']) && $this->post['language'][$language->id]['is_online'] ? 'checked' : '') ?>> <?= $this->translate('is_online_language') ?>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="" class="col-sm-2 control-label"><?= $this->translate('title') ?></label>
                        <div class="col-sm-10">
                            <input type="text" name="language[<?= $language->id ?>][title]" class="form-control" value="<?= !empty($this->post['language'][$language->id]['title']) ? $this->post['language'][$language->id]['title'] : '' ?>">
                            <?= $this->_messenger->display($this->partial('formfield_error.phtml'), 'title'.$language->id, 8) ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="" class="col-sm-2 control-label"><?= $this->translate('content') ?></label>
                        <div class="col-sm-10">
                            <textarea name="language[<?= $language->id ?>][content]" class="form-control ckeditor"><?= !empty($this->post['language'][$language->id]['content']) ? $this->post['language'][$language->id]['content'] : '' ?></textarea>
                            <?= $this->_messenger->display($this->partial('formfield_error.phtml'), 'content'.$language->id, 8) ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <hr>
    </div>
    <div class="form-group">
        <label for="" class="col-sm-2 control-label"><?= $this->translate('category') ?></label>
        <div class="col-sm-10">
            <select name="category_id" class="form-control">
                <option value="0"><?= $this->translate('choose_category') ?></option>
                <?php foreach ($this->categories as $category): ?>
                    <option <?= isset($this->post['category_id']) && $this->post['category_id'] == $category->id ? 'selected' : '' ?> value="<?= $category->id ?>"><?= $category->category_contents[0]->name ?></option>
                <?php endforeach; ?>
            </select>
            <?= $this->_messenger->display($this->partial('formfield_error.phtml'), 'category_id', 8) ?>
        </div>
    </div>
    <div class="form-group">
        <label for="" class="col-sm-2 control-label"><?= $this->translate('publish_date') ?></label>
        <div class="col-sm-10">
            <input type="text" name="publish_date" class="form-control datetime publish_date" value="<?= !empty($this->post['publish_date']) ? $this->post['publish_date'] : '' ?>">
            <?= $this->_messenger->display($this->partial('formfield_error.phtml'), 'publish_date', 8) ?>
        </div>
    </div>
    <div class="form-group">
        <label for="" class="col-sm-2 control-label"><?= $this->translate('archive_date') ?></label>
        <div class="col-sm-10">
            <input type="text" name="archive_date" class="form-control datetime2 archive_date" value="<?= !empty($this->post['archive_date']) ? $this->post['publish_date'] : '' ?>">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <div class="checkbox">
                <label>
                    <input <?= isset($this->post['allow_comments']) && $this->post['allow_comments'] ? 'checked' : '' ?> name="allow_comments" value="1" type="checkbox"> <?= $this->translate('allow_comments') ?>
                </label>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <div class="checkbox">
                <label>
                    <input <?= isset($this->post['is_online']) && $this->post['is_online'] ? 'checked' : '' ?> name="is_online" value="1" type="checkbox"> <?= $this->translate('is_online') ?>
                </label>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button name="save_article" type="submit" class="btn btn-xl btn-primary"><?= $this->translate('save') ?></button>
        </div>
    </div>
</form>
