<form class="form-horizontal" method="post">
    <div>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <?php foreach ($this->languages as $language): ?>
                <li role="presentation" <?= $language->is_default ? 'class="active"' : '' ?>><a href="#<?= $language->iso_code ?>" aria-controls="<?= $language->iso_code ?>" role="tab" data-toggle="tab"><?= $this->translate($language->iso_code) ?></a></li>
            <?php endforeach; ?>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <?php foreach ($this->languages as $language): ?>
                <div role="tabpanel" class="tab-pane <?= $language->is_default ? 'active' : '' ?>" id="<?= $language->iso_code ?>">
                    <div class="form-group">
                        <label for="" class="col-sm-2 control-label"><?= $this->translate('name') ?></label>
                        <div class="col-sm-10">
                            <input type="text" name="language[<?= $language->id ?>][name]" class="form-control" value="<?= $this->post['language'][$language->id]['name'] ?? '' ?>">
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <hr>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <div class="checkbox">
                <label>
                    <input <?= isset($this->post['is_enabled']) && $this->post['is_enabled'] ? 'checked' : '' ?> name="is_enabled" value="1" type="checkbox"> <?= $this->translate('is_enabled') ?>
                </label>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <div class="checkbox">
                <label>
                    <input <?= isset($this->post['is_online']) && $this->post['is_online'] ? 'checked' : '' ?> name="is_online" value="1" type="checkbox"> <?= $this->translate('is_online') ?>
                </label>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button name="save_category" type="submit" class="btn btn-xl btn-primary"><?= $this->translate('save') ?></button>
        </div>
    </div>
</form>

