<?php
$this->_helper->appendJSFile('datatables/datatables.min.js');
$this->_helper->appendJSFile('datatables/datatables.bootstrap.min.js');
$this->_helper->appendJSInline('
    $(document).ready(function() {
        $(".table").DataTable({
            "language": ' . $this->translate('datatable_language') . ',
            "order": [[ 3, "desc" ]],
            "columnDefs": [{
                "orderable": false, "targets": [0, 4],
            }],
            "columns": [
              { "width": "20px" },
              null,
              { "width": "65px" },
              { "width": "65px" },
              { "width": "160px" }
            ]
        });
    });
');
$this->_helper->appendCSSFile('datatables/datatables.min.css');
echo $this->partial('admin_index_table.phtml', [
    'fields' => [
            [
            'field' => 'id',
            'type' => 'primary_key',
            'label' => 'ID'
        ],
            [
            'field' => 'category_contents[0]->name',
            'type' => '',
            'label' => 'Title'
        ],
            [
            'field' => 'is_online',
            'type' => 'boolean',
            'label' => 'Online'
        ],
            [
            'field' => 'is_enabled',
            'type' => 'boolean',
            'label' => 'Enabled'
        ]
    ],
    'messages' => null,
    'items' => $this->categories,
    'modulename' => 'blog',
    'modulehandler' => 'categories',
    'permissions' => $this->permissions
]);
