<?php foreach ($this->articles as $article): ?>
    <article>
        <h2><a href="/article/<?= $article->id ?>"><?= $article->title ?></a></h2>
        <p><?= $article->content ?></p>
        <hr>
        <span><?= $this->translate('posted_on') ?>: <?= $this->_helper->my_strftime($this->translate('strftime'), $article->publish_date->getTimestamp()) ?></span> - <span><?= $this->translate('category') ?>: <?= $article->name ?></span>
    </article>
<?php endforeach; ?>
