<article>
    <h2><a href="/article/<?= $article->id ?>"><?= $this->article->article_contents[0]->title ?></a></h2>
    <p><?= $this->article->article_contents[0]->content ?></p>
    <hr>
    <span>Datum: <?= strftime('%A, %e %B %Y', $this->article->publish_date->getTimestamp()) ?></span> <span>Category: <?= $this->article->category->category_contents[0]->name ?></span>
</article>
<?= $this->comments ?>
<?= $this->commentform ?>