<p>
    Dear <?= $this->fullname ?>,
</p>
<p>
    You have requested to reset your password. By following the link below you can do so.<br>
    <a href="<?= $this->_router->getURLByRouteName('admin/reset-password/token', ['token' => $this->token], true) ?>"><?= $this->_router->getURLByRouteName('admin/reset-password/token', ['token' => $this->token], true) ?></a>
</p>
<p>
    This link will be valid till <?= $this->_helper->my_strftime($this->translate('strftime'), $this->expire_date->getTimestamp()) ?>.<br>
    In case you have not requested a password reset link then please ignore this email.
</p>
<p>
    Kind regards,
</p>
<p>
    Domain.tld
</p>
