<p>
    Beste <?= $this->fullname ?>,
</p>
<p>
    Je hebt bij ons een verzoek ingediend om je wachtwoord te resetten. Dit kan je doen door op de onderstaande link te klikken.<br>
    <a href="<?= $this->_router->getURLByRouteName('admin/reset-password/token', ['token' => $this->token], true) ?>"><?= $this->_router->getURLByRouteName('admin/reset-password/token', ['token' => $this->token], true) ?></a>
</p>
<p>
    Deze link is geldig tot <?= $this->_helper->my_strftime($this->translate('strftime'), $this->expire_date->getTimestamp()) ?>.<br>
    Heb je geen wachtwoord reset aangevraagd? Dan kan je deze e-mail negeren.
</p>
<p>
    Met vriendelijke groet,
</p>
<p>
    Domain.tld
</p>
