<?php
$this->_helper->appendJSInline('
    $(".model-id-selector").on("click", function(){
        $("#mass-actions").addClass("disabled");
        $(".model-id-selector").each(function(){
            if ($(this).is(":checked")) {
                $("#mass-actions").removeClass("disabled");
            }
        });
    });
    $(".delete-single").on("click", function() {
        $("#singleModal").modal({backdrop: "static"});
        $("#item_id").val($(this).attr("data-id"));
    });
    $(".delete-multi").on("click", function() {
        $("#multiModal").modal({backdrop: "static"});
        $(".model-id-selector").each(function(){
            if ($(this).is(":checked")) {
                $("#multiDeleteForm").append("<input name=item_id[] type=hidden value=" + $(this).val() + ">");
            }
        });
    });
');
?>
<div class="modal fade" id="singleModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form class="form-horizontal" action="/admin/<?= $this->modulename ?>/<?= $this->modulehandler ?>/delete" method="post">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel"><?= $this->translate('delete ' . $this->modulename . '') ?></h4>
                </div>
                <div class="modal-body">
                    <input name="item_id" type="hidden" id="item_id">
                    <?= $this->translate('delete ' . $this->modulename . ' confirmation') ?>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?= $this->translate('Cancel') ?></button>
                    <button type="submit" class="btn btn-danger"><?= $this->translate('delete') ?></button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="multiModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="multiDeleteForm" class="form-horizontal" action="/admin/<?= $this->modulename ?>/<?= $this->modulehandler ?>/delete" method="post">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel"><?= $this->translate('delete ' . $this->modulename . '') ?></h4>
                </div>
                <div class="modal-body">
                    <input name="item_id" type="hidden" id="item_id">
                    <?= $this->translate('delete ' . $this->modulename . ' confirmation') ?>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?= $this->translate('Cancel') ?></button>
                    <button type="submit" class="btn btn-danger"><?= $this->translate('delete') ?></button>
                </div>
            </form>
        </div>
    </div>
</div>
<?= $this->_messages->display($this->partial('alert.phtml')) ?>
<table class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
            <?php foreach ($this->fields as $field): ?>
                <?php if ($field['type'] == 'primary_key'): ?>
                    <th>#<?= $this->translate($field['label']) ?></th>
                <?php else: ?>
                    <th><?= $this->translate($field['label']) ?></th>
                <?php endif; ?>
            <?php endforeach; ?>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->items as $item): ?>
            <tr>
                <?php foreach ($this->fields as $field): ?>
                    <?php if ($field['type'] == 'primary_key'): ?>
                        <td><input class="model-id-selector" type="checkbox" value="<?= $this->_helper->getClassProperty($item, $field['field']) ?>"></td>
                    <?php elseif ($field['type'] == 'boolean'): ?>
                        <td><?= $this->_helper->getClassProperty($item, $field['field']) ? '<span class="label label-success">' . $this->translate('yes') . '</span>' : '<span class="label label-danger">' . $this->translate('no') . '</span>' ?></td>
                    <?php else: ?>
                        <td><?= $this->_helper->getClassProperty($item, $field['field']) ?></td>
                    <?php endif; ?>
                <?php endforeach; ?>
                <td>
                    <?php if ($this->permissions['update']): ?>
                        <a href="/admin/<?= $this->modulename ?>/<?= $this->modulehandler ?>/edit/<?= $item->id ?>" class="btn btn-sm btn-default"><?= $this->translate('edit') ?></a>
                    <?php endif; ?>
                    <?php if ($this->permissions['delete']): ?>
                        <button data-id="<?= $item->id ?>" type="button" class="btn btn-sm btn-danger delete-single"><?= $this->translate('delete') ?></button>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <?php foreach ($this->fields as $key => $field): ?>
                <?php if ($field['type'] == 'primary_key'): ?>
                    <th>#<?= $this->translate($field['label']) ?></th>
                <?php else: ?>
                    <th><?= $this->translate($field['label']) ?></th>
                <?php endif; ?>
            <?php endforeach; ?>
            <th></th>
        </tr>
        <tr>
            <td colspan="8">
                <div class="btn-toolbar" role="toolbar" aria-label="...">
                    <div class="btn-group pull-left" role="group" aria-label="...">
                        <?php if ($this->permissions['create']): ?>
                            <a href="/admin/<?= $this->modulename ?>/<?= $this->modulehandler ?>/add" class="btn btn-success"><?= $this->translate('add') ?></a>
                        <?php endif; ?>
                    </div>
                    <div class="btn-group pull-right" role="group" aria-label="...">
                        <button id="mass-actions" type="button" class="btn disabled btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <?= $this->translate('with_selected') ?> <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu multi-level">
                            <li class="dropdown-submenu">
                                <a href="#">More...</a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <?php if ($this->permissions['delete']): ?>
                                <li role="separator" class="divider"></li>
                                <li><a class="delete-multi" href="#"><?= $this->translate('delete') ?></a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
            </td>
        </tr>
    </tfoot>
</table>
