<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <title>...</title>
    <?= $this->helper()->getCSS() ?>  
</head>
<body>
    <div class="container">
        <?= $this->content ?>
    </div>
    <?= $this->helper()->getJS() ?>
</body>
</html>
