<form class="form-horizontal" method="post">
    <div>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <?php foreach ($this->languages as $language): ?>
                <li role="presentation" <?= $language->is_default ? 'class="active"' : ''?>><a href="#<?= $language->iso_code ?>" aria-controls="<?= $language->iso_code ?>" role="tab" data-toggle="tab"><?= $this->translate($language->iso_code) ?></a></li>
            <?php endforeach; ?>
        </ul>
        <hr>
        <!-- Tab panes -->
        <div class="tab-content">
            <?php foreach ($this->languages as $language): ?>
                <div role="tabpanel" class="tab-pane <?= $language->is_default ? 'active' : ''?>" id="<?= $language->iso_code ?>">
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <div class="checkbox">
                                <label>
                                    <?php if ($language->is_default): ?>
                                        <input type="hidden" name="language[<?= $language->id ?>][is_online]" value="1">
                                        <?php else: ?>
                                        <input type="hidden" name="language[<?= $language->id ?>][is_online]" value="0">
                                    <?php endif; ?>
                                    <input type="checkbox" name="language[<?= $language->id ?>][is_online]" value="1" <?= $language->is_default ? 'checked disabled' : ($this->category->language[$language->id]['is_online'] ? 'checked' : '') ?>> <?= $this->translate('is_online_language') ?>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="" class="col-sm-2 control-label"><?= $this->translate('name') ?></label>
                        <div class="col-sm-10">
                            <input type="text" name="language[<?= $language->id ?>][name]" class="form-control" value="<?= isset($this->category->language[$language->id]['name']) ? $this->category->language[$language->id]['name'] : '' ?>">
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <hr>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <div class="checkbox">
                <label>
                    <input name="is_enabled" <?= $this->category->is_enabled ? 'checked' : '' ?> value="1" type="checkbox"> <?= $this->translate('is_enabled') ?>
                </label>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <div class="checkbox">
                <label>
                    <input name="is_online" <?= $this->category->is_online ? 'checked' : '' ?> value="1" type="checkbox"> <?= $this->translate('is_online') ?>
                </label>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-xl btn-primary"><?= $this->translate('save') ?></button>
        </div>
    </div>
</form>
