<?php
$this->helper()->appendCSSFile('/static/css/datatables/dataTables.bootstrap.min.css');
$this->helper()->appendCSSFile('/static/css/datepicker/bootstrap-datetimepicker.min.css');

$this->helper()->appendJSFile('/static/js/moment/moment.min.js');
$this->helper()->appendJSFile('/static/js/datatables/dataTables.min.js');
$this->helper()->appendJSFile('/static/js/datatables/dataTables.bootstrap.min.js');
$this->helper()->appendJSFile('/static/js/datepicker/bootstrap-datetimepicker.min.js');
$this->helper()->appendJSInline('
    $(document).ready(function() {
        $(".table").DataTable({
            "language": '. $this->translate('datatable_language') .',
            "order": [[ 1, "desc" ]],
            "columnDefs": [{
                "orderable": false, "targets": [0, 4],
            }],
            "columns": [
              { "width": "20px" },
              null,
              { "width": "80px" },
              { "width": "115px" },
              { "width": "195px" }
            ]
        });
        $(".delete-single").on("click", function() {
            $("#singleModal").modal({backdrop: "static"});
        });
    });
');
?>
<?= $this->partial('admin_index_table.phtml', array(
    'modulename' => 'category',
    'fields' => array(
        'id' => array(
            'label' => 'ID',
            'type' => 'primary_key',
        ),
        'name' => array(
            'label' => 'name',
            'type' => 'string',
        ),
        'is_enabled' => array(
            'label' => 'is_enabled',
            'type' => 'boolean',
        ),
        'is_online' => array(
            'label' => 'is_online',
            'type' => 'boolean',
        ),
    ),
    'items' => $this->categories,
    'messages' => $this->messages,
)) ?>