<form class="form-horizontal" method="post">
    <div>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <?php foreach ($this->languages as $language): ?>
                <li role="presentation" <?= $language->is_default ? 'class="active"' : ''?>><a href="#<?= $language->iso_code ?>" aria-controls="<?= $language->iso_code ?>" role="tab" data-toggle="tab"><?= $this->translate($language->iso_code) ?></a></li>
            <?php endforeach; ?>
        </ul>
        <hr>
        <!-- Tab panes -->
        <div class="tab-content">
            <?php foreach ($this->languages as $language): ?>
                <div role="tabpanel" class="tab-pane <?= $language->is_default ? 'active' : ''?>" id="<?= $language->iso_code ?>">
                    <div class="form-group">
                        <label for="" class="col-sm-2 control-label"><?= $this->translate('name') ?></label>
                        <div class="col-sm-10">
                            <input type="text" name="language[<?= $language->id ?>][name]" class="form-control" value="<?= isset($this->group->language[$language->id]['name']) ? $this->group->language[$language->id]['name'] : '' ?>">
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <hr>
    </div>
    <div class="form-group">
        <label for="" class="col-sm-2 control-label"><?= $this->translate('group_role') ?></label>
        <div class="col-sm-10">
            <table class="table">
                <thead>
                <tr>
                    <th></th>
                    <?php foreach($this->actions as $action): ?>
                        <th><?= $this->translate($action->name . '_action') ?></th>
                    <?php endforeach; ?>
                </tr>
                </thead>
                <tbody>
                <?php foreach($this->modules as $module): ?>
                    <tr>
                        <td><?= $this->translate($module->name . '_module') ?></td>
                        <?php foreach($this->actions as $action): ?>
                            <td>
                                <input <?= isset($this->group->group_roles[$module->id]) && ((int) $this->group->group_roles[$module->id] & (int) $action->value) == (int) $action->value ? 'checked' : '' ?> name="group_role[<?= $module->id ?>][<?= $action->id ?>]" value="<?= $action->value ?>" type="checkbox">
                            </td>
                        <?php endforeach; ?>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <div class="checkbox">
                <label>
                    <input name="is_enabled" <?= $this->group->is_enabled ? 'checked' : '' ?> value="1" type="checkbox"> <?= $this->translate('is_enabled') ?>
                </label>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-xl btn-primary"><?= $this->translate('save') ?></button>
        </div>
    </div>
</form>
