<div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#"></a>
</div>
<div id="navbar" class="collapse navbar-collapse">
    <?php

    function showMenu($menu) {
        $html = '<ul class="nav navbar-nav">';
        foreach($menu as $item) {
            $html .= '<li class="">';
            if (count($item->children)) {
                $html .= '<a href="' . $item->url . '">' . $item->link . '</a>';
                $html .= showMenu($item->children);
            } else {
                $html .= '<a href="' . $item->url . '">' . $item->link . '</a>';
            }
            $html .= '</li>';
        }
        $html .= '</ul>';
        return $html;
    }
    echo showMenu($this->menu);
    ?>
</div>