<div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#"></a>
</div>
<div id="navbar" class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
        <li class=""><a href="/admin/user/list"><span class="label label-default"><?= $this->translate('admin_link_users') ?></span></a></li>
        <li class=""><a href="/admin/group/list"><span class="label label-default"><?= $this->translate('admin_link_groups') ?></span></a></li>
        <li class=""><a href="#"><span class="label label-primary"><?= $this->translate('admin_link_pages') ?></span></a></li>
        <li class=""><a href="/admin/article/list"><span class="label label-info"><?= $this->translate('admin_link_articles') ?></span></a></li>
        <li class=""><a href="/admin/category/list"><span class="label label-info"><?= $this->translate('admin_link_categories') ?></span></a></li>
        <li class=""><a href="#"><span class="label label-info"><?= $this->translate('admin_link_paragraphs') ?></span></a></li>
    </ul>
</div>