<!-- Piwik -->
<script type="text/javascript">
    var _paqinit = _paqinit || false;
    var _paq = _paq || [];
    _paq.push(['setDocumentTitle', '%[width]%x%[height]%_%[platform]%_%[nr]%']);
    _paq.push(['trackVisibleContentImpressions', true, 750]);
    _paq.push(['setCustomVariable',1,"Type","<?= $this->tool_type ?>","page"]);
    _paq.push(['setCustomVariable',2,"Platform","<?= $this->platform ?>","page"]);

    (function() {
        var u="//<?= $this->tracker_domain ?>/";
        if (!_paqinit) {
            _paq.push(['setTrackerUrl', u+'js/']);
            _paq.push(['setSiteId', <?= $this->tracker_website_id ?>]);
            _paqinit = true;
        }
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'js/'; s.parentNode.insertBefore(g,s);
    })();
</script>
<noscript><p><img src="//<?= $this->tracker_domain ?>/js/?idsite=<?= $this->tracker_website_id ?>" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->